// <auto-generated />
using System;
using GoalGoalPredict.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoalGoalPredict.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612075655_AddMatchVarDecisions")]
    partial class AddMatchVarDecisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.CardPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PredictionId");

                    b.ToTable("card_predictions", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.GoalscorerPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Normal Goal")
                        .HasColumnName("goal_type");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PredictionId");

                    b.ToTable("goalscorer_predictions", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsSimulation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_simulation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.GroupScoringRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardPredictionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("card_prediction_mode");

                    b.Property<bool>("ExactScoreEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("exact_score_enabled");

                    b.Property<int>("ExactScorePoints")
                        .HasColumnType("integer")
                        .HasColumnName("exact_score_points");

                    b.Property<bool>("GoalscorerEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("goalscorer_enabled");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<bool>("MissedPenaltyEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("missed_penalty_enabled");

                    b.Property<int>("MissedPenaltyMaxPicks")
                        .HasColumnType("integer")
                        .HasColumnName("missed_penalty_max_picks");

                    b.Property<int>("MissedPenaltyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("missed_penalty_points");

                    b.Property<bool>("OutcomeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("outcome_enabled");

                    b.Property<int>("OutcomePoints")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_points");

                    b.Property<bool>("OwnGoalEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("own_goal_enabled");

                    b.Property<int>("OwnGoalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("own_goal_points");

                    b.Property<bool>("RedCardEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("red_card_enabled");

                    b.Property<int>("RedCardMaxPicks")
                        .HasColumnType("integer")
                        .HasColumnName("red_card_max_picks");

                    b.Property<int>("RedCardPoints")
                        .HasColumnType("integer")
                        .HasColumnName("red_card_points");

                    b.Property<int>("ScorerAttPoints")
                        .HasColumnType("integer")
                        .HasColumnName("scorer_att_points");

                    b.Property<int>("ScorerDefPoints")
                        .HasColumnType("integer")
                        .HasColumnName("scorer_def_points");

                    b.Property<int>("ScorerGkPoints")
                        .HasColumnType("integer")
                        .HasColumnName("scorer_gk_points");

                    b.Property<int>("ScorerMidPoints")
                        .HasColumnType("integer")
                        .HasColumnName("scorer_mid_points");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WrongPickPenalty")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_pick_penalty");

                    b.Property<bool>("YellowCardEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("yellow_card_enabled");

                    b.Property<int>("YellowCardMaxPicks")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_card_max_picks");

                    b.Property<int>("YellowCardPoints")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_card_points");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "MatchId")
                        .IsUnique();

                    b.ToTable("group_scoring_rules", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<int?>("ElapsedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_minutes");

                    b.Property<int?>("ExtraTimeAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("et_away_goals");

                    b.Property<int?>("ExtraTimeHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("et_home_goals");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finished");

                    b.Property<DateTime>("KickoffUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_utc");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<bool>("LineupRevealNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lineup_reveal_notified");

                    b.Property<bool>("LineupsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("lineups_available");

                    b.Property<int?>("PenaltyAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("pen_away_goals");

                    b.Property<int?>("PenaltyHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("pen_home_goals");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("round");

                    b.Property<Guid?>("SimulationGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_group_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ApiFootball")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiEventOrder")
                        .HasColumnType("integer")
                        .HasColumnName("api_event_order");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("card_type");

                    b.Property<int?>("ExtraMinute")
                        .HasColumnType("integer")
                        .HasColumnName("extra_minute");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "ApiEventOrder")
                        .IsUnique();

                    b.ToTable("match_cards", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiEventOrder")
                        .HasColumnType("integer")
                        .HasColumnName("api_event_order");

                    b.Property<int?>("ExtraMinute")
                        .HasColumnType("integer")
                        .HasColumnName("extra_minute");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("goal_type");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int?>("ScorerPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("scorer_player_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("ScorerPlayerId");

                    b.HasIndex("MatchId", "ApiEventOrder")
                        .IsUnique();

                    b.ToTable("match_goals", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchLineupPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsStarting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_starting");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("position");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("integer")
                        .HasColumnName("shirt_number");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("match_lineup_players", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchSubstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiEventOrder")
                        .HasColumnType("integer")
                        .HasColumnName("api_event_order");

                    b.Property<int?>("ExtraMinute")
                        .HasColumnType("integer")
                        .HasColumnName("extra_minute");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int?>("PlayerInId")
                        .HasColumnType("integer")
                        .HasColumnName("player_in_id");

                    b.Property<int?>("PlayerOutId")
                        .HasColumnType("integer")
                        .HasColumnName("player_out_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerInId");

                    b.HasIndex("PlayerOutId");

                    b.HasIndex("MatchId", "ApiEventOrder")
                        .IsUnique();

                    b.ToTable("match_substitutions", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchVarDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiEventOrder")
                        .HasColumnType("integer")
                        .HasColumnName("api_event_order");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("detail");

                    b.Property<int?>("ExtraMinute")
                        .HasColumnType("integer")
                        .HasColumnName("extra_minute");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "ApiEventOrder")
                        .IsUnique();

                    b.ToTable("match_var_decisions", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("integer")
                        .HasColumnName("shirt_number");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<bool>("IsScored")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scored");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "MatchId", "GroupId")
                        .IsUnique();

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.PredictionScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<int>("ExactScorePoints")
                        .HasColumnType("integer")
                        .HasColumnName("exact_score_points");

                    b.Property<int>("GoalscorerPoints")
                        .HasColumnType("integer")
                        .HasColumnName("goalscorer_points");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("MissedPenaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("missed_penalty_points");

                    b.Property<int>("OutcomePoints")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_points");

                    b.Property<int>("OwnGoalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("own_goal_points");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.Property<int>("RedCardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("red_card_points");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YellowCardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("yellow_card_points");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId")
                        .IsUnique();

                    b.ToTable("prediction_scores", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.SimulationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("card_type");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Goal")
                        .HasColumnName("event_kind");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("goal_type");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("simulation_events", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.CardPrediction", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Prediction", "Prediction")
                        .WithMany("CardPredictions")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.GoalscorerPrediction", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Prediction", "Prediction")
                        .WithMany("GoalscorerPredictions")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Match", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchCard", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany("Cards")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchGoal", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany("Goals")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Scorer")
                        .WithMany()
                        .HasForeignKey("ScorerPlayerId");

                    b.Navigation("Match");

                    b.Navigation("Scorer");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchLineupPlayer", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany("LineupPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchSubstitution", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany("Substitutions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "PlayerIn")
                        .WithMany()
                        .HasForeignKey("PlayerInId");

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "PlayerOut")
                        .WithMany()
                        .HasForeignKey("PlayerOutId");

                    b.Navigation("Match");

                    b.Navigation("PlayerIn");

                    b.Navigation("PlayerOut");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.MatchVarDecision", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany("VarDecisions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Player", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.PredictionScore", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Prediction", "Prediction")
                        .WithOne("Score")
                        .HasForeignKey("GoalGoalPredict.Domain.Entities.PredictionScore", "PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.SimulationEvent", b =>
                {
                    b.HasOne("GoalGoalPredict.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalGoalPredict.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Match", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Goals");

                    b.Navigation("LineupPlayers");

                    b.Navigation("Substitutions");

                    b.Navigation("VarDecisions");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Prediction", b =>
                {
                    b.Navigation("CardPredictions");

                    b.Navigation("GoalscorerPredictions");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("GoalGoalPredict.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
